# -*- coding: utf-8 -*-
"""samplepycode

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iaeuefGFiC3lwojuA_G-NXDAikLVtXXZ
"""

name=input("Enter name")
print(name)